# Legacy pattern threshold is kept because the old pattern modules remain available for research.
MIN_PATTERN_SCORE = 65.0

MIN_HISTORY_BARS = 80
MAX_QUESTIONS_PER_TICKER = 30
CHART_LOOKBACK_BARS = 45
FUTURE_DISPLAY_BARS = 20

MIN_FEATURE_STRENGTH = 0.42
MIN_ACTIVE_FEATURES = 3
PRIMARY_FEATURE_COUNT = 4
MIN_CHART_INTEREST_SCORE = 52.0
MAX_DIFFICULTY_SCORE = 45.0
