HOME_PRODUCTS = [
    {
        "id": 101,
        "brandName": "DERMA LAB",
        "productName": "PDRN 리페어 앰플",
        "reactionScore": 94,
        "scoreChange": 8,
        "daysSinceLaunch": 9,
        "reviewCount": 396,
        "discountRate": 30,
        "status": "HOT",
        "tags": ["PDRN", "탄력", "광채"],
        "benefits": ["탄력", "보습", "광채"],
        "metrics": {
            "reviewVelocity": 98,
            "rating": 92,
            "discount": 82,
            "oliveyoungExposure": 95,
            "freshness": 94,
            "earlyReaction": 97,
            "snsBuzz": 88,
        },
        "art": {"label": "PDRN", "accent": "#FF7F9E", "soft": "#FFE7EF"},
    },
    {
        "id": 102,
        "brandName": "AUREA",
        "productName": "글로우 비타 세럼",
        "reactionScore": 91,
        "scoreChange": 13,
        "daysSinceLaunch": 12,
        "reviewCount": 288,
        "discountRate": 25,
        "status": "HOT",
        "tags": ["비타민", "잡티", "광채"],
        "benefits": ["잡티", "광채"],
        "metrics": {
            "reviewVelocity": 96,
            "rating": 90,
            "discount": 76,
            "oliveyoungExposure": 90,
            "freshness": 89,
            "earlyReaction": 93,
            "snsBuzz": 91,
        },
        "art": {"label": "VITA", "accent": "#FFB24A", "soft": "#FFF1D7"},
    },
    {
        "id": 103,
        "brandName": "CALMING 365",
        "productName": "시카 수딩 앰플",
        "reactionScore": 88,
        "scoreChange": 5,
        "daysSinceLaunch": 6,
        "reviewCount": 171,
        "discountRate": 20,
        "status": "RISING",
        "tags": ["시카", "진정", "민감"],
        "benefits": ["진정", "보습"],
        "metrics": {
            "reviewVelocity": 91,
            "rating": 94,
            "discount": 70,
            "oliveyoungExposure": 84,
            "freshness": 97,
            "earlyReaction": 90,
            "snsBuzz": 80,
        },
        "art": {"label": "CICA", "accent": "#55B88A", "soft": "#E1F6EC"},
    },
]
