create table if not exists public.cafes (
  id bigint generated by default as identity primary key,
  external_source text,
  external_place_id text unique,
  name text not null,
  region_code text not null,
  region_name text not null,
  address text not null,
  latitude double precision not null,
  longitude double precision not null,
  views jsonb not null default '{}'::jsonb,
  sunset_view_score smallint not null default 0 check (sunset_view_score between 0 and 5),
  open_view_score smallint not null default 0 check (open_view_score between 0 and 5),
  cafe_quality_score smallint not null default 0 check (cafe_quality_score between 0 and 5),
  view_description text not null default '',
  best_seat_tip text not null default '',
  kakao_map_url text,
  active boolean not null default true,
  view_direction_deg double precision,
  view_direction_confidence double precision not null default 0 check (view_direction_confidence between 0 and 1),
  view_direction_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cafe_photos (
  id bigint generated by default as identity primary key,
  cafe_id bigint not null unique references public.cafes(id) on delete cascade,
  image_url text not null,
  storage_path text not null unique,
  uploaded_by text,
  status text not null default 'PENDING' check (status in ('PENDING','APPROVED','REJECTED')),
  content_type text not null,
  width integer,
  height integer,
  file_size_bytes bigint,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  moderation_note text
);

create index if not exists idx_cafes_view_region
  on public.cafes(region_code)
  where active = true;

create index if not exists idx_cafe_photos_status
  on public.cafe_photos(status);

alter table public.cafes enable row level security;
alter table public.cafe_photos enable row level security;

revoke all on public.cafes from anon, authenticated;
revoke all on public.cafe_photos from anon, authenticated;
grant all on public.cafes to service_role;
grant all on public.cafe_photos to service_role;
grant usage, select on all sequences in schema public to service_role;

create policy "deny_direct_cafe_access"
on public.cafes
as restrictive
for all
to anon, authenticated
using (false)
with check (false);

create policy "deny_direct_photo_access"
on public.cafe_photos
as restrictive
for all
to anon, authenticated
using (false)
with check (false);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'cafe-photos',
  'cafe-photos',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types,
  updated_at = now();
